model_list:
 - model_name: "gpt-3.5-turbo"
   llm_params:
    model: azure/chatgpt-v-2
    api_key: os.environ/AZURE_API_KEY
    api_base: http://0.0.0.0:8090
    rpm: 3
 - model_name: "gpt-4o-mini-openai"
   llm_params:
    model: gpt-4o-mini
    api_key: os.environ/OPENAI_API_KEY
 - model_name: "bedrock-nova"
   llm_params:
    model: us.amazon.nova-pro-v1:0

llm_settings:
  num_retries: 0

router_settings:
  routing_strategy: usage-based-routing-v2 # ðŸ‘ˆ KEY CHANGE
  redis_host: os.environ/REDIS_HOST
  redis_password: os.environ/REDIS_PASSWORD
  redis_port: os.environ/REDIS_PORT

general_settings:
  enable_jwt_auth: True
  llm_jwtauth:
    admin_jwt_scope: "ai.admin"
    # team_id_jwt_field: "client_id" # ðŸ‘ˆ CAN BE ANY FIELD
    user_id_jwt_field: "sub" # ðŸ‘ˆ CAN BE ANY FIELD
    org_id_jwt_field: "org_id" # ðŸ‘ˆ CAN BE ANY FIELD
    end_user_id_jwt_field: "customer_id" # ðŸ‘ˆ CAN BE ANY FIELD
    user_id_upsert: True